// Generated by scripts/plugin-spec.ts from src/fxmic/spec.ts — do not edit.
//
// The EP-2350's effects, parameters and ranges, transcribed from the user
// guide (ver 1.1.1) chapter 7 and, where marked unverified, from a config that
// a player with the hardware published. See the TypeScript for the reasoning
// behind every number; this file is only its shadow.
#pragma once

namespace spec
{
struct Param
{
    const char* name;
    float min, max, start;
};

struct Effect
{
    const char* name;
    const char* label;
    bool oncePerChain;
    bool unverified;
    const Param* params;
    int numParams;
};

inline constexpr Param delayParams[] = {
    { "time", 0.0f, 1.1f, 0.4f },
    { "echo", 0.0f, 1.0f, 0.4f },
    { "cross-feed", 0.0f, 1.0f, 0.0f },
    { "lowpass-cutoff", 0.0f, 1.0f, 1.0f },
    { "highpass-cutoff", 0.0f, 1.0f, 0.0f },
    { "wet-level", 0.0f, 1.0f, 0.5f },
    { "dry-level", 0.0f, 1.0f, 1.0f },
    { "balance", 0.0f, 1.0f, 0.5f },
};

inline constexpr Param distParams[] = {
    { "amount", 0.0f, 40.0f, 10.0f },
    { "mix", 0.0f, 1.0f, 0.5f },
    { "lowpass-cutoff", 0.0f, 1.0f, 1.0f },
    { "highpass-cutoff", 0.0f, 1.0f, 0.0f },
};

inline constexpr Param equaliserParams[] = {
    { "cutoff", 0.0f, 1.0f, 0.5f },
    { "q", 0.0f, 1.0f, 0.5f },
    { "gain", -1.0f, 1.0f, 0.0f },
};

inline constexpr Param harmonyParams[] = {
    { "pitch", 0.5f, 2.0f, 1.0f },
    { "dry-level", 0.0f, 1.0f, 1.0f },
};

inline constexpr Param lowpassParams[] = {
    { "cutoff", 0.0f, 1.0f, 1.0f },
};

inline constexpr Param highpassParams[] = {
    { "cutoff", 0.0f, 1.0f, 0.0f },
};

inline constexpr Param sampleParams[] = {
    { "speed", 0.0f, 4.0f, 1.0f },
    { "pitch", -24.0f, 24.0f, 0.0f },
    { "level", 0.0f, 1.0f, 1.0f },
    { "balance", 0.0f, 1.0f, 0.5f },
};

inline constexpr Param reverbParams[] = {
    { "time", 0.0f, 1.0f, 0.4f },
    { "wet-level", 0.0f, 1.0f, 0.4f },
    { "dry-level", 0.0f, 1.0f, 1.0f },
    { "spring-mix", 0.0f, 1.0f, 0.0f },
    { "highpass-cutoff", 0.0f, 1.0f, 0.0f },
};

inline constexpr Param ringParams[] = {
    { "frequency", 0.0f, 20000.0f, 200.0f },
    { "mix", 0.0f, 1.0f, 0.5f },
};

inline constexpr Param ssbParams[] = {
    { "frequency", -20000.0f, 20000.0f, 0.0f },
};

inline constexpr Param balanceParams[] = {
    { "balance", 0.0f, 1.0f, 0.5f },
};

inline constexpr Effect effects[] = {
    { "DELAY", "delay", true, false, delayParams, 8 },
    { "DIST", "dist", false, false, distParams, 4 },
    { "EQUALISER", "equaliser", false, false, equaliserParams, 3 },
    { "HARMONY", "harmony", true, false, harmonyParams, 2 },
    { "LOWPASS", "lowpass", false, false, lowpassParams, 1 },
    { "HIGHPASS", "highpass", false, false, highpassParams, 1 },
    { "SAMPLE", "sample", false, false, sampleParams, 4 },
    { "REVERB", "reverb", true, false, reverbParams, 5 },
    { "RING", "ring", false, false, ringParams, 2 },
    { "SSB", "ssb", true, false, ssbParams, 1 },
    { "BALANCE", "balance", false, true, balanceParams, 1 },
};

inline constexpr int numEffects = 11;

/** The LFO's shapes, in the order config.json names them. */
inline constexpr const char* lfoShapes[] = { "sine", "square", "sawtooth", "random" };
inline constexpr int numLfoShapes = 4;

inline const Effect* effectByName (const char* name)
{
    for (auto& e : effects)
    {
        auto* a = e.name;
        auto* b = name;
        while (*a != 0 && *a == *b) { ++a; ++b; }
        if (*a == 0 && *b == 0)
            return &e;
    }
    return nullptr;
}

/** A parameter's published start value — what the device uses when a config omits it. */
inline float startValue (const Effect& e, const char* param)
{
    for (int i = 0; i < e.numParams; ++i)
    {
        auto* a = e.params[i].name;
        auto* b = param;
        while (*a != 0 && *a == *b) { ++a; ++b; }
        if (*a == 0 && *b == 0)
            return e.params[i].start;
    }
    return 0.0f;
}
} // namespace spec
