/**
 * npm run plugin-spec — regenerates the plugin's copy of the device spec.
 *
 * Same rule as the zine: a second description of the mic that can disagree
 * with the first is worse than none, so the C++ never gets its own hand-typed
 * table of ranges. Edit src/fxmic/spec.ts and run this.
 */
import { writeFileSync } from 'node:fs'
import { EFFECTS, LFO_SHAPES, type EffectSpec } from '../src/fxmic/spec.ts'

const ident = (name: string) => name.toLowerCase().replace(/[^a-z0-9]/g, '')

const f = (n: number) => (Number.isInteger(n) ? `${n}.0f` : `${n}f`)

const params = (e: EffectSpec) =>
  `inline constexpr Param ${ident(e.name)}Params[] = {\n` +
  e.params.map((p) => `    { "${p.name}", ${f(p.min)}, ${f(p.max)}, ${f(p.start)} },`).join('\n') +
  '\n};\n'

const effect = (e: EffectSpec) =>
  `    { "${e.name}", "${e.label}", ${e.oncePerChain}, ${!!e.unverified}, ` +
  `${ident(e.name)}Params, ${e.params.length} },`

const body = `// Generated by scripts/plugin-spec.ts from src/fxmic/spec.ts — do not edit.
//
// The EP-2350's effects, parameters and ranges, transcribed from the user
// guide (ver 1.1.1) chapter 7 and, where marked unverified, from a config that
// a player with the hardware published. See the TypeScript for the reasoning
// behind every number; this file is only its shadow.
#pragma once

namespace spec
{
struct Param
{
    const char* name;
    float min, max, start;
};

struct Effect
{
    const char* name;
    const char* label;
    bool oncePerChain;
    bool unverified;
    const Param* params;
    int numParams;
};

${EFFECTS.map(params).join('\n')}
inline constexpr Effect effects[] = {
${EFFECTS.map(effect).join('\n')}
};

inline constexpr int numEffects = ${EFFECTS.length};

/** The LFO's shapes, in the order config.json names them. */
inline constexpr const char* lfoShapes[] = { ${LFO_SHAPES.map((s) => `"${s}"`).join(', ')} };
inline constexpr int numLfoShapes = ${LFO_SHAPES.length};

inline const Effect* effectByName (const char* name)
{
    for (auto& e : effects)
    {
        auto* a = e.name;
        auto* b = name;
        while (*a != 0 && *a == *b) { ++a; ++b; }
        if (*a == 0 && *b == 0)
            return &e;
    }
    return nullptr;
}

/** A parameter's published start value — what the device uses when a config omits it. */
inline float startValue (const Effect& e, const char* param)
{
    for (int i = 0; i < e.numParams; ++i)
    {
        auto* a = e.params[i].name;
        auto* b = param;
        while (*a != 0 && *a == *b) { ++a; ++b; }
        if (*a == 0 && *b == 0)
            return e.params[i].start;
    }
    return 0.0f;
}
} // namespace spec
`

const out = new URL('../plugin/Source/Spec.generated.h', import.meta.url)
writeFileSync(out, body)
console.log(`wrote ${out.pathname} — ${EFFECTS.length} effects`)
